name: dicoding_news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  webview_flutter: ^4.7.0
  google_fonts: ^4.0.3
  http: ^1.2.1
  android_alarm_manager_plus: ^4.0.3
  flutter_local_notifications: ^17.1.2
  rxdart: ^0.27.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/berita.json
